force-app/main/default/objects/Chatter_Setting__c/Chatter_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Chatter Setting</label>
</CustomObject>

force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <label>Date Booked</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>RUB</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/tests/TradesListViewControllerTest.cls
@isTest
private class TradesListViewControllerTest {
    private static final String QUEUE_NAME = 'Trade reviewers';

    @isTest
    private static void getTradeListNegative() {
        List<Trade__c> tradeList = TradesListViewController.getTradeList();
        System.assertEquals(tradeList.size(), 0, 'Trade List is not empty');
    }

    @isTest
    private static void getTradeListWithoutQueueNameNegative() {
        try {
            createTrades(5);
            List<Trade__c> tradeList = TradesListViewController.getTradeList();
            System.assertEquals(tradeList.size(), 0, 'Trade List is not empty');
        } catch (Exception ex) {
            System.assert(ex.getMessage().contains('Cannot create Chatter post: Fill in the name of the queue in the custom Chatter Setting'));
        }
    }

    @isTest(SeeAllData=true)
    private static void getTradeListPositive() {
        try {
            createChatterSetting();
            createTrades(5);
            List<Trade__c> tradeList = TradesListViewController.getTradeList();
            System.assert(!tradeList.isEmpty(), 'Trade List is empty');
        } catch (Exception ex) {
            System.assert(ex.getMessage().length() == 0, 'Unexpected error');
        }
    }

    private static void createChatterSetting() {
        if (Chatter_Setting__c.getOrgDefaults()?.Queue_Name__c == null) {
            insert new Chatter_Setting__c(Queue_Name__c = QUEUE_NAME);
        }
    }


    private static void createTrades(Integer count) {
        List<Trade__c> tradeList = new List<Trade__c>();

        for (Integer i = 0; i < count; i++) {
            tradeList.add(new Trade__c(
                Sell_Currency__c = 'EUR',
                Sell_Amount__c = i,
                Buy_Currency__c = 'USD',
                Buy_Amount__c = i,
                Rate__c = i,
                Date_Booked__c = Datetime.now()
            ));
        }

        insert tradeList;
    }

}