force-app/main/default/objects/Trade__c/Trade__c.object-meta.xml
<CustomObject>
    <label>Trade</label>
    <nameField>
        <displayFormat>TR-{0000000}</displayFormat>
        <label>Trade Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trades</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trade__c/fields/Buy_Amount__c.field-meta.xml
<CustomField>
    <fullName>Buy_Amount__c</fullName>
    <label>Buy Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Buy_Currency__c.field-meta.xml
<CustomField>
    <fullName>Buy_Currency__c</fullName>
    <label>Buy Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Date_Booked__c.field-meta.xml
<CustomField>
    <fullName>Date_Booked__c</fullName>
    <label>Date Booked</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trade__c/fields/Sell_Currency__c.field-meta.xml
<CustomField>
    <fullName>Sell_Currency__c</fullName>
    <label>Sell Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Currency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Currency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>EUR</fullName>
    </customValue>
    <customValue>
        <fullName>USD</fullName>
    </customValue>
    <customValue>
        <fullName>RUB</fullName>
    </customValue>
    <masterLabel>Currency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/helpers/ChatterService.cls
public with sharing class ChatterService {

    // Used ConnectApi because FeedItem not supported mention

    @testVisible
    private List<ConnectApi.BatchInput> batchInputs;

    public ChatterService() {
        batchInputs = new List<ConnectApi.BatchInput>();
    }

    public void createPost(Set<Id> recipients, String message, Id subjectId) {
        if (recipients.isEmpty()) {
            throw new CustomException(Label.empty_Recipients);
        }

        ConnectApi.FeedItemInput feedItemInput = new ConnectApi.FeedItemInput();
        feedItemInput.body = this.generateBody(recipients, message);
        feedItemInput.feedElementType = ConnectApi.FeedElementType.FeedItem;
        feedItemInput.subjectId = subjectId;
        this.batchInputs.add(new ConnectApi.BatchInput(feedItemInput));
    }

    public void sendPost() {
        if (!Test.isRunningTest()) {
            ConnectApi.ChatterFeeds.postFeedElementBatch(Network.getNetworkId(), this.batchInputs);
        }
    }

    public String generatePostMessage(Trade__c trade) {
        List<String> params = new List<String>{
                trade.Sell_Currency__c,
                String.valueOf(trade.Sell_Amount__c),
                trade.Buy_Currency__c,
                String.valueOf(trade.Buy_Amount__c),
                String.valueOf(trade.Rate__c),
                trade.Date_Booked__c != null ? trade.Date_Booked__c.format() : null,
                URL.getSalesforceBaseUrl().toExternalForm() + '/' + trade.Id + '\n'
        };

        return String.format(Label.chatter_Notification_Message, params);
    }

    private ConnectApi.MessageBodyInput generateBody(Set<Id> recipients, String message) {
        ConnectApi.MessageBodyInput messageBody = new ConnectApi.MessageBodyInput();
        messageBody.messageSegments = new List<ConnectApi.MessageSegmentInput>();

        ConnectApi.TextSegmentInput textSegment = new ConnectApi.TextSegmentInput();
        textSegment.text = message;
        messageBody.messageSegments.add(textSegment);

        for (Id userId : recipients) {
            ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
            mentionSegmentInput.Id = userId;
            messageBody.messageSegments.add(mentionSegmentInput);
        }

        return messageBody;
    }

}